import { defineConfig, globalIgnores } from 'eslint/config';
import prettierRecommended from 'eslint-plugin-prettier/recommended';
import globals from 'globals';
import tseslint from 'typescript-eslint';

export default defineConfig([
  // src/data-contracts is generated by swagger-typescript-api and ships its own
  // `/* eslint-disable */` header, so it is not linted here.
  globalIgnores(['dist/**', 'src/data-contracts/**']),
  {
    files: ['**/*.ts'],
    extends: [...tseslint.configs.recommended, prettierRecommended],
    languageOptions: {
      ecmaVersion: 2018,
      sourceType: 'module',
      globals: {
        ...globals.node,
      },
    },
    rules: {
      '@typescript-eslint/explicit-member-accessibility': 'off',
      '@typescript-eslint/explicit-function-return-type': 'off',
      '@typescript-eslint/explicit-module-boundary-types': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-require-imports': 'off',
      // typescript-eslint v8 split the old `ban-types` rule (which this project
      // had turned off) into these three rules.
      '@typescript-eslint/no-unsafe-function-type': 'off',
      '@typescript-eslint/no-wrapper-object-types': 'off',
      '@typescript-eslint/no-empty-object-type': 'off',
    },
  },
  {
    // Ambient declaration files import types purely to drive module augmentation.
    files: ['**/*.d.ts'],
    rules: {
      '@typescript-eslint/no-unused-vars': 'off',
    },
  },
]);
